name: Deploy to Firebase
on:
  push:
    branches:
      - firebase

env:
  FIREBASE_TOKEN: "1//0cQaXlkC55gWoCgYIARAAGAwSNwF-L9Ir5sGecdEMyzq2Sr-iKMETnJbrlTGIjBhtNy1EaqUAlN8ji3JTG5rLAwrrHQtdb7CmFQU"

jobs:
  checkout:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - name: Install dependencies
        run: npm install
      - name: Run Build
        run: npm run build
      - name: Install Firebase
        run: npm install firebase
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      - name: Deploy to Firebase
        run: firebase deploy --token "$FIREBASE_TOKEN"
